# C/C++ with GCC
# Build your C/C++ project with GCC using make.
# Add steps that publish test results, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/c-cpp/gcc
pr:
  - master
  - release_*

pool:
  vmImage: 'ubuntu-18.04'

variables:
- name: one
  value: initialValue 
   
jobs:
  - job: runcheck
    steps:
      - bash: sudo apt-get install -y pep8
      - bash: .github/runchecks

  - job: c8_build_test
    dependsOn: runcheck
    variables:
    - name: OS_TYPE
      value: "centos:8"
    steps:
    - bash: docker pull $(OS_TYPE)
    - bash: docker run -it -d -h pbs.dev.local --name pbsdev -v $(pwd):$(pwd) --privileged -w $(pwd) $(OS_TYPE) /bin/bash
    - bash: docker exec   --privileged pbsdev .travis/do.sh

  - job: suse15_build_test
    dependsOn: runcheck
    variables:
    - name: OS_TYPE
      value: "opensuse/leap:15"
    - name: DOCKER_EXTRA_ARG
      value: "-e LC_ALL=C.utf8" 
    steps:
    - bash: docker pull $(OS_TYPE)
    - bash: docker run -it $(DOCKER_EXTRA_ARG) -d -h pbs.dev.local --name pbsdev -v $(pwd):$(pwd) --privileged -w $(pwd) $(OS_TYPE) /bin/bash
    - bash: docker exec  --privileged pbsdev .travis/do.sh

  - job: u2004_build_test
    dependsOn: runcheck
    variables:
    - name: OS_TYPE
      value: "ubuntu:20.04"
    - name: DOCKER_EXTRA_ARG
      value: "-e DEBIAN_FRONTEND=noninteractive -e LANGUAGE=C.UTF-8 -e LANG=C.UTF-8 -e LC_ALL=C.UTF-8" 
    steps:
    - bash: docker pull $(OS_TYPE)
    - bash: docker run -it  $(DOCKER_EXTRA_ARG) -d -h pbs.dev.local --name pbsdev -v $(pwd):$(pwd) --privileged -w $(pwd) $(OS_TYPE) /bin/bash
    - bash: docker exec   --privileged pbsdev .travis/do.sh

  - job: c7_sanitize_build_test
    dependsOn: runcheck
    variables:
    - name: OS_TYPE
      value: "centos:7"
    - name: DOCKER_EXTRA_ARG
      value: "-e LC_ALL=en_US.utf-8 -e LANG=en_US.utf-8" 
    steps:
    - bash: docker pull $(OS_TYPE)
    - bash: docker run -it -e BUILD_MODE=sanitize $(DOCKER_EXTRA_ARG) -d -h pbs.dev.local --name pbsdev -v $(pwd):$(pwd) --privileged -w $(pwd) $(OS_TYPE) /bin/bash
    - bash: docker exec   --privileged pbsdev .travis/do_sanitize_mode.sh
    
  - job: c7_kerberos_build
    dependsOn: runcheck
    variables:
    - name: OS_TYPE
      value: "centos:7"
    - name: DOCKER_EXTRA_ARG
      value: "-e LC_ALL=en_US.utf-8 -e LANG=en_US.utf-8" 
    steps:
    - bash: docker pull $(OS_TYPE)
    - bash: docker run -it -e BUILD_MODE=kerberos $(DOCKER_EXTRA_ARG) -d -h pbs.dev.local --name pbsdev -v $(pwd):$(pwd) --privileged -w $(pwd) $(OS_TYPE) /bin/bash
    - bash: docker exec   --privileged pbsdev .travis/do.sh
