# C/C++ with GCC
# Build your C/C++ project with GCC using make.
# Add steps that publish test results, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/c-cpp/gcc
pr:
  - master
  - release_*

pool:
  vmImage: 'ubuntu-18.04'

variables:
  - name: OS_TYPE
    values: "centos:8", "ubuntu:20.04"
    
jobs:
  - job: runcheck
    steps:
      - bash: sudo apt-get install -y pep8
      - bash: .github/runchecks
  - job: pbs_build_test
    dependsOn: runcheck
    strategy:
      matrix:
        C8_build_test:
             OS_TYPE: "centos:8"
        #S15_build_test:
        #   variables:
        #     - name: OS_TYPE
        #       value: "opensuse/leap:15"
        #     - name: DOCKER_EXTRA_ARG
        #       value: "-e LC_ALL=C.utf8"
        U20_build_test:
             OS_TYPE: "ubuntu:20.04"
             DOCKER_EXTRA_ARG: "-e DEBIAN_FRONTEND=noninteractive -e LANGUAGE=C.UTF-8 -e LANG=C.UTF-8 -e LC_ALL=C.UTF-8" 
    steps:
    - bash: docker pull $(OS_TYPE)
    - bash: docker run -it $(DOCKER_EXTRA_ARG) -d -h pbs.dev.local --name pbsdev -v $(pwd):$(pwd) --privileged -w $(pwd) $(OS_TYPE) /bin/bash
    - bash: docker exec   --privileged pbsdev .travis/do.sh
    
